Add `.clang-tidy`
mchalupa/dg pull request #385
Opened 2021-04-07 12:07 UTC by lzaoral

This PR adds a (relatively) reasonable configuration for `clang-tidy` that should mainly focus on readability and modern C++.
If some check that you find useful is missing or there are some checks that you dislike, please tell me.

2021-05-07 13:04 UTC, mchalupa requested changes
It would be nice if you could (at least for now) turn off these checks:

`readability-implicit-bool-conversion`
`llvm-namespace-comment`

The first one we violate rather willingly and the later one complaints about the format of the comments even though we have some. We can focus on these once we solved the other (I think more important) suggestions.

2021-05-07 13:48 UTC, lzaoral commented
Hmm, It looks that the global reformat in 2e60545c73a872b95d3c32a097e351ed9bfd8bf6 broke everything 😕. No offence intended, but it would be definitely safer if you tried to do every change in its own branch and merge it into `master` iff the CI is green (or the CI failure is unrelated).

2021-05-11 13:48 UTC, lzaoral commented
I've already sent a patch to SVF last week (https://github.com/SVF-tools/SVF/pull/434), so that should be fixed as well. It's quite scary that their CI didn't catch that. On the other hand, using their `master` in our CI probably isn't the best idea either. 🤔

2021-05-12 08:48 UTC, lzaoral commented
I've rebased the PR and everything is green now. Thanks!

2021-05-13 10:33 UTC, mchalupa commented
Then let's merge this. Thanks!

2021-05-13 10:33 UTC, merged