VR: use fixed and refactored version
mchalupa/dg pull request #403
Opened 2021-10-05 11:40 UTC by GiraffeReversed

Known issues:

- release build has problems, since when building llvm-vr-dump, it is being linked with Release-built libraries dgvra and dgllvmvra, which therefore do not contain necessary dump methods; the build therefore fails (and I am not sure how to fix that)
- the CMakeLists.txt both in dg were changed because the source files were split between `.h` and `.cpp` files; the linking during build of `llvm-vr-dump` has been changed accordingly, but the solution probably has some issues
- the augmentation adds no incorrect answers, as tested on benchmarks from SV-COMP 2020 (the 2021 test in under way)
- the sleep-1 benchmark from busybox has been found faulty by the unaugmented version but timeouts with the new one, nevertheless I was not able to reproduce the success with the unaugmented version after that; when comparing the sliced ll files (i think), I have found no difference

I would prefer to go over the issues in person as to learn more from them :)

2021-10-05 18:51 UTC, lzaoral requested changes
General remarks regarding style and CMake related stuff as I'm not skilled enough to understand the code itself:

- Many files do not end with a newline. (I think that `git` issues a warning when files with white-space errors are committed.)
- Some header guards end with `_` and some do not.
- Use `'\n'` instead of `std::endl` as it has an unnecessary overhead due to flushing and it is completely useless with `std::cerr` as it is an unbuffered stream.
- Just to be sure:
    - Did you format all commits with `git clang-format`?
    - Did you apply all relevant `clang-tidy` suggestions?
- Please fix all warnings issued in the Ubuntu CI jobs that ale relevant to your code.
- If you need some help with the linker errors in CI, just let me know as this stuff can be a real nightmare. The Debug macOS job is probably the best place to start as `ld` on macOS is much stricter in terms of coping with undefined symbols. By default both `ld.bfd` and `ld.lld` are ok with underlinked dynamic libraries and report undefined symbols only in executables. However, macOS's `ld` fails with underlinked dynamic libraries as well. You can additionally add `-Wl,--no-undefined` to `LDFLAGS` and use `Debug` as a build type to get a similar behaviour on a Linux machine. Generally, underlinking is a phenomenon that should be avoided [as can be seen here](https://wiki.mageia.org/en/Underlinking_issues_in_packaging#Why_underlinking_is_bad).

2021-10-05 18:51 UTC, lzaoral commented on include/dg/llvm/ValueRelations/ValueRelations.h
> +#endif
This should not be needed since 6e9e004b6078949be87f981140577382f301e178.

2021-10-05 18:51 UTC, lzaoral commented on lib/CMakeLists.txt
> +	llvm/ValueRelations/GraphElements.cpp
Sort these please.

2021-10-05 18:51 UTC, lzaoral commented on lib/CMakeLists.txt
> +
Superfluous newline.

2021-10-05 18:51 UTC, lzaoral commented on tools/CMakeLists.txt
>  				PRIVATE ${llvm_core}
Please re-add the comments and add libraries above it in sorted order.

2021-10-05 18:51 UTC, lzaoral commented on tests/value-relations-test.cpp
> +#include "catch.hpp"
This should be `#include <catch2/catch.hpp>`.

2021-10-05 18:51 UTC, lzaoral commented on tests/CMakeLists.txt
> +include_directories(${CMAKE_SOURCE_DIR}/include)
This line is already present in this file.

2021-10-05 18:51 UTC, lzaoral commented on tests/CMakeLists.txt
> +include_directories(${CMAKE_CURRENT_BINARY_DIR})
This should redundant after you fix the Catch 2 include.

2021-10-05 18:51 UTC, lzaoral commented on tests/CMakeLists.txt
> +                                            PRIVATE ${llvm_support})
Please, remove the one space so that the `PRIVATE`'s are centred and sort the LLVM includes.

2021-10-05 18:51 UTC, lzaoral commented on tests/CMakeLists.txt
> +target_compile_options(value-relations-test PRIVATE -Wall -Wextra -pedantic -g ${COLORS})
This line should not be be required as all these flags have already been set at this point and `COLORS` is undefined.

2021-10-05 18:53 UTC, lzaoral commented on tests/CMakeLists.txt
> +include_directories(${CMAKE_SOURCE_DIR}/include)
Sorry, I accidentally selected more lines than I intended. The comment above refers to line 207 only.

2021-10-05 18:57 UTC, lzaoral commented on lib/CMakeLists.txt
> +# target_link_libraries(dgllvmvra PUBLIC dgvra dganalysis)
Please remove the commentary on line 224.

2021-10-09 09:13 UTC, lzaoral commented
@GiraffeReversed If you haven't looked into the linking issues yet, you can apply this commit https://github.com/lzaoral/dg/commit/971dff3832cc26f1f1d6ff63f73371329da459e0. The macOS and Ubuntu 20.04 jobs now compile successfully but the the `value-releations-tests` fails as ASAN found some [use after free](https://github.com/lzaoral/dg/runs/3845808690?check_suite_focus=true). Just pass `-DUSE_SANITIZERS=ON` to CMake to check it locally.

2021-10-14 07:07 UTC, lzaoral commented
Please, ignore the broken Ubuntu 16.04 jobs. #404 fixes the issue so don't forget to rebase after it's merged.

2021-10-14 11:57 UTC, lzaoral commented
GitHub's macOS VMs have been just switched to LLVM 13, so that failure should be fixed by #404 as well.

2021-10-16 07:53 UTC, lzaoral commented
Sorry for the CI issues. they are caused by https://github.com/mchalupa/dg/pull/404#issuecomment-944402769. #406 should fix them for real.

2021-11-03 09:24 UTC, GiraffeReversed commented
I rebased on master here and in staticafi/sbt-instrumentation#65.

2021-11-16 18:00 UTC, mchalupa commented
When I compile instrumentation with sanitizers and run symbiotic on `ldv-memsafety/memleaks_test13_1.i` from sv-benchmarks:
```
scripts/symbiotic --witness witness.graphml --sv-comp --prp ../sv-benchmarks/c/properties/valid-memsafety.prp --32 --slicer-params='-annotate=slice' --save-files ../sv-benchmarks/c/ldv-memsafety/memleaks_test13_1.i
```
I get this error:

```
==30985==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f0000a3b48 at pc 0x7fb7a3893ec6 bp 0x7ffc1565f9f0 sp 0x7ffc1565f9e0
READ of size 8 at 0x60f0000a3b48 thread T0
    #0 0x7fb7a3893ec5 in std::vector<llvm::Value const*, std::allocator<llvm::Value const*> >::size() const /usr/include/c++/11.1.0/bits/stl_vector.h:919
    #1 0x7fb7a3838500 in dg::vr::ValueRelations::hasComparativeRelations(dg::vr::EqualityBucket*) const /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:649
    #2 0x7fb7a3838eea in dg::vr::ValueRelations::hasComparativeRelationsOrLoads(dg::vr::EqualityBucket*) const /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:656
    #3 0x7fb7a384e4c5 in dg::vr::ValueRelations::unsetAllLoadsByPtr(llvm::Value const*) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:1410
    #4 0x7fb7a3873667 in dg::vr::RelationsAnalyzer::forgetInvalidated(dg::vr::ValueRelations&, llvm::Instruction const*) const /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:68
    #5 0x7fb7a3873055 in dg::vr::RelationsAnalyzer::processOperation(dg::vr::VRLocation*, dg::vr::VRLocation*, dg::vr::VROp*) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:52
    #6 0x7fb7a388a324 in dg::vr::RelationsAnalyzer::analysisPass() /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:1205
    #7 0x7fb7a388abd3 in dg::vr::RelationsAnalyzer::analyze(unsigned int) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:1226
    #8 0x7fb7a38124d8 in ValueRelationsPlugin::ValueRelationsPlugin(llvm::Module*) /home/marek/src/symbiotic/sbt-instrumentation/analyses/value_relations_plugin.cpp:22
    #9 0x7fb7a38164d6 in create_object /home/marek/src/symbiotic/sbt-instrumentation/analyses/value_relations_plugin.cpp:190
    #10 0x55955ece3312 in Analyzer::analyze(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llvm::Module*) /home/marek/src/symbiotic/sbt-instrumentation/src/instr_analyzer.cpp:38
    #11 0x55955ec762a5 in loadPlugins(LLVMInstrumentation&) /home/marek/src/symbiotic/sbt-instrumentation/src/instr.cpp:1315
    #12 0x55955ec796ba in main /home/marek/src/symbiotic/sbt-instrumentation/src/instr.cpp:1409
    #13 0x7fb7a70b5b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #14 0x55955ec5cded in _start (/home/marek/src/symbiotic/sbt-instrumentation/build-10.0.1/src/sbt-instr+0x3c5ded)

0x60f0000a3b48 is located 152 bytes inside of 168-byte region [0x60f0000a3ab0,0x60f0000a3b58)
freed by thread T0 here:
    #0 0x7fb7a8fc8d69 in operator delete(void*, unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x7fb7a3995fa5 in std::default_delete<dg::vr::EqualityBucket>::operator()(dg::vr::EqualityBucket*) const /usr/include/c++/11.1.0/bits/unique_ptr.h:85
    #2 0x7fb7a39864ea in std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >::~unique_ptr() /usr/include/c++/11.1.0/bits/unique_ptr.h:361
    #3 0x7fb7a39667db in void __gnu_cxx::new_allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > >::destroy<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > >(std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >*) /usr/include/c++/11.1.0/ext/new_allocator.h:162
    #4 0x7fb7a39307ef in void std::allocator_traits<std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > > >::destroy<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > >(std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > >&, std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >*) /usr/include/c++/11.1.0/bits/alloc_traits.h:531
    #5 0x7fb7a38e25c8 in std::vector<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >, std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > > >::_M_erase(__gnu_cxx::__normal_iterator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >*, std::vector<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >, std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > > > >) /usr/include/c++/11.1.0/bits/vector.tcc:177
    #6 0x7fb7a38a102e in std::vector<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >, std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > > >::erase(__gnu_cxx::__normal_iterator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > const*, std::vector<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> >, std::allocator<std::unique_ptr<dg::vr::EqualityBucket, std::default_delete<dg::vr::EqualityBucket> > > > >) /usr/include/c++/11.1.0/bits/stl_vector.h:1431
    #7 0x7fb7a38178b4 in eraseUniquePtr<dg::vr::EqualityBucket> /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:42
    #8 0x7fb7a384e45a in dg::vr::ValueRelations::unsetAllLoadsByPtr(llvm::Value const*) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:1408
    #9 0x7fb7a3873667 in dg::vr::RelationsAnalyzer::forgetInvalidated(dg::vr::ValueRelations&, llvm::Instruction const*) const /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:68
    #10 0x7fb7a3873055 in dg::vr::RelationsAnalyzer::processOperation(dg::vr::VRLocation*, dg::vr::VRLocation*, dg::vr::VROp*) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:52
    #11 0x7fb7a388a324 in dg::vr::RelationsAnalyzer::analysisPass() /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:1205
    #12 0x7fb7a388abd3 in dg::vr::RelationsAnalyzer::analyze(unsigned int) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:1226
    #13 0x7fb7a38124d8 in ValueRelationsPlugin::ValueRelationsPlugin(llvm::Module*) /home/marek/src/symbiotic/sbt-instrumentation/analyses/value_relations_plugin.cpp:22
    #14 0x7fb7a38164d6 in create_object /home/marek/src/symbiotic/sbt-instrumentation/analyses/value_relations_plugin.cpp:190
    #15 0x55955ece3312 in Analyzer::analyze(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llvm::Module*) /home/marek/src/symbiotic/sbt-instrumentation/src/instr_analyzer.cpp:38
    #16 0x55955ec762a5 in loadPlugins(LLVMInstrumentation&) /home/marek/src/symbiotic/sbt-instrumentation/src/instr.cpp:1315
    #17 0x55955ec796ba in main /home/marek/src/symbiotic/sbt-instrumentation/src/instr.cpp:1409
    #18 0x7fb7a70b5b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)

previously allocated by thread T0 here:
    #0 0x7fb7a8fc7ca1 in operator new(unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fb7a3847cfa in dg::vr::ValueRelations::ValueRelations(dg::vr::ValueRelations const&) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:1148
    #2 0x7fb7a3872f90 in dg::vr::RelationsAnalyzer::processOperation(dg::vr::VRLocation*, dg::vr::VRLocation*, dg::vr::VROp*) /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/RelationsAnalyzer.h:47
    #3 0x7fb7a388a324 in dg::vr::Rela [...]

2021-11-16 20:44 UTC, GiraffeReversed commented
I am having trouble reproducing this problem. When I compile dg configured with USE_SANITIZERS=On and analyze the code with llvm-vr-dump, I get no error.

I suspect there might be something wrong with the build, since when I compile symbiotic on dg with the option set, I get `ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.` as part of the error -- nevertheless, I have no clue as to what might be wrong.

2021-11-16 21:06 UTC, lzaoral commented
@GiraffeReversed Try this: Compile `dg` with GCC and sanitizers and run the script with
```console
$ LD_PRELOAD="$(gcc -print-file-name=libasan.so)" ASAN_OPTIONS=detect_leaks=0 scripts/symbiotic ...
```

2021-11-16 21:14 UTC, GiraffeReversed commented
@mchalupa Are you sure you tested the updated version? I renamed the EqualityBucket class as part of the refactoring, yet the error trace mentions it.

2021-11-16 21:47 UTC, GiraffeReversed commented
The fix suggested by @lzaoral did fix the problem (in the sense that the error does no longer show). Nevertheless when I run symbiotic like this, I get `INFO: Starting instrumentation` followed by `INFO: Instrumentation [FAILED] time: 0.00809025764465332`, with no indication what the problem is in between.

2021-11-16 22:09 UTC, mchalupa commented
> @mchalupa Are you sure you tested the updated version? I renamed the EqualityBucket class as part of the refactoring, yet the error trace mentions it.

I'll re-check. It is possible that I did not recompile everything properly.

2021-11-23 15:50 UTC, mchalupa commented
Ok, I have now tested this PR quite well and I do not have enough strength to go commit-by-commit, so I'll just believe the commits are nice and tidy :) Let's merge this.

2021-11-23 15:50 UTC, merged